version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=sqs
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack

  postgres:
    image: postgres:latest
    container_name: local-postgres
    environment:
      POSTGRES_USER: dummy
      POSTGRES_PASSWORD: dummy
      POSTGRES_DB: financial
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  localstack_data:
  postgres-data:

