spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/financial
    username: dummy
    password: dummy
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  aws:
    sqs:
      endpoint: http://localhost:4566
      region: us-east-1
      access-key: dummy
      secret-key: dummy

logging:
  level:
    root: INFO
